### ISSUE TITLE
Usage with Docusaurus

### ISSUE THREAD

**Issue by jcubic** [patorjk/figlet.js#127]
When using with Docusaurus SSG that use Webpack. Got this error:

```
[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (/home/kuba/projects/jcubic/terminal/repo/docusaurus/docs/node_modules/@docusaurus/core/lib/commands/build.js:54:19)
    at async /home/kuba/projects/jcubic/terminal/repo/docusaurus/docs/node_modules/@docusaurus/core/lib/commands/build.js:65:9
    at async mapAsyncSequential (/home/kuba/projects/jcubic/terminal/repo/docusaurus/docs/node_modules/@docusaurus/utils/lib/jsUtils.js:21:24)
    at async Command.build (/home/kuba/projects/jcubic/terminal/repo/docusaurus/docs/node_modules/@docusaurus/core/lib/commands/build.js:63:5) {
  [cause]: Error: Docusaurus static site generation failed for 1 paths:
  - "/jquery.terminal-docs/"
      at generateStaticFiles (/home/kuba/projects/jcubic/terminal/repo/docusaurus/docs/node_modules/@docusaurus/core/lib/ssg.js:86:15)
      at async executeSSG (/home/kuba/projects/jcubic/terminal/repo/docusaurus/docs/node_modules/@docusaurus/core/lib/commands/build.js:174:23)
      ... 4 lines matching cause stack trace ...
      at async Command.build (/home/kuba/projects/jcubic/terminal/repo/docusaurus/docs/node_modules/@docusaurus/core/lib/commands/build.js:63:5) {
    [cause]: AggregateError
        at generateStaticFiles (/home/kuba/projects/jcubic/terminal/repo/docusaurus/docs/node_modules/@docusaurus/core/lib/ssg.js:87:20)
        at async executeSSG (/home/kuba/projects/jcubic/terminal/repo/docusaurus/docs/node_modules/@docusaurus/core/lib/commands/build.js:174:23)
        at async buildLocale (/home/kuba/projects/jcubic/terminal/repo/docusaurus/docs/node_modules/@docusaurus/core/lib/commands/build.js:134:31)
        at async tryToBuildLocale (/home/kuba/projects/jcubic/terminal/repo/docusaurus/docs/node_modules/@docusaurus/core/lib/commands/build.js:47:13)
        at async /home/kuba/projects/jcubic/terminal/repo/docusaurus/docs/node_modules/@docusaurus/core/lib/commands/build.js:65:9
        at async mapAsyncSequential (/home/kuba/projects/jcubic/terminal/repo/docusaurus/docs/node_modules/@docusaurus/utils/lib/jsUtils.js:21:24)
        at async Command.build (/home/kuba/projects/jcubic/terminal/repo/docusaurus/docs/node_modules/@docusaurus/core/lib/commands/build.js:63:5) {
      [errors]: [
        Error: Can't render static file for pathname "/jquery.terminal-docs/"
            at generateStaticFile (/home/kuba/projects/jcubic/terminal/repo/docusaurus/docs/node_modules/@docusaurus/core/lib/ssg.js:119:15)
            at async /home/kuba/projects/jcubic/terminal/repo/docusaurus/docs/node_modules/p-map/index.js:57:22 {
          [cause]: ReferenceError: __dirname is not defined
              at 1542 (server.bundle.js:11906:23)
              at __webpack_require__ (server.bundle.js:21939:42)
              at 2935 (server.bundle.js:9574:19)
              at __webpack_require__ (server.bundle.js:21939:42)
              at server.bundle.js:3346:1331
        }
      ]
    }
  }
}
```

I use browser API but that code is executed on runtime, the error is triggered on build, when importing `figlet`.

Chaning this code:

```javascript
import figlet from 'figlet';
```

to:

```javascript
import figlet from 'figlet/lib/figlet.js';
```

But there are no types for this import.

**Comment by jcubic** [comment]
To use with Docusaurus you need to add a plugin that will create an alias in webpack:

```javascript
export default function WebpackPlugin() {
  return {
    name: 'webpack',
    configureWebpack() {
      return {
        resolve: {
          alias: {
            'figlet': 'figlet/lib/figlet.js'
          }
        }
      };
    }
  };
}
```

and add into `docusaurus.config.ts`:

```javascript
plugins: ['./src/plugins/webpack.ts'],
```
